name: Teh
version: '1.0-SNAPSHOT'
main: net.hynse.teh.Teh
api-version: '1.21'
folia-supported: true
softdepend:
  - PlaceholderAPI
commands:
  tehreload:
    description: Reloads the Teh plugin configuration.
    usage: /tehreload
    permission: teh.reload
  toggleteh:
    description: Toggle your health indicator display.
    usage: /toggleteh
    permission: teh.indicator.toggle